// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyfV70mGAelce2J6PelPTvfJxry35GX8',
    appId: '1:758445440171:web:097cb0f2dde6e98fef8bee',
    messagingSenderId: '758445440171',
    projectId: 'recipes-app-b8651',
    authDomain: 'recipes-app-b8651.firebaseapp.com',
    storageBucket: 'recipes-app-b8651.appspot.com',
    measurementId: 'G-9Q536RJST6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlb75uw-Nf6u49oguL6rsG_jiAXMXIa0',
    appId: '1:758445440171:android:b5036a6f15846c51ef8bee',
    messagingSenderId: '758445440171',
    projectId: 'recipes-app-b8651',
    storageBucket: 'recipes-app-b8651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8cC0dwMtXFuKnvp8uDlvYH1csLWqhdE',
    appId: '1:758445440171:ios:7acf449d7d75f6c0ef8bee',
    messagingSenderId: '758445440171',
    projectId: 'recipes-app-b8651',
    storageBucket: 'recipes-app-b8651.appspot.com',
    iosClientId: '758445440171-k6kucagj55ja31pdcr1vj8mkp279aemf.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw8cC0dwMtXFuKnvp8uDlvYH1csLWqhdE',
    appId: '1:758445440171:ios:67eb68c6e5aea798ef8bee',
    messagingSenderId: '758445440171',
    projectId: 'recipes-app-b8651',
    storageBucket: 'recipes-app-b8651.appspot.com',
    iosClientId: '758445440171-0ivcn4e1h0sbd39v7hk8k1mpcjcekkt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipesApp.RunnerTests',
  );
}
